apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: sonarr
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8989
    name: sonarr80
#  - protocol: TCP
#    port: 8989
#    targetPort: 8989
#    name: sonarr8989
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sonarr
  namespace: sonarr
  labels:
    app: sonarr
subsets:
- addresses:
  - ip: 192.168.1.200
  ports:
  - port: 8989
    name: sonarr8989
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: sonarr
spec:
  rules:
  - host: sonarr.control.local
    http:
      paths:
      - backend:
          service:
            name: sonarr
            port:
             number: 80
        path: "/"
        pathType: Prefix
