apiVersion: v1
kind: Service
metadata:
  name: sonarr-tcp
  namespace: sonarr
  annotations:
    metallb.universe.tf/address-pool: sonarr
    metallb.universe.tf/allow-shared-ip: sonarr
  labels:
    app: sonarr
spec:
  type: LoadBalancer
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 8989 
    targetPort: 8989 
    name: 8989-sonarr
  - protocol: TCP
    port: 80
    targetPort: 8989
    name: 80-8989-sonarr

