apiVersion: v1
kind: Namespace
metadata:
  name: sonarr
  labels:
    app: sonarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-config-volume
  namespace: sonarr
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/bigdata/storage/configs/sonarr/
    server: 192.168.1.60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pv-config-claim
  namespace: sonarr
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-media-volume
  namespace: sonarr
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 7300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/bigdata/storage
    server: 192.168.1.60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pv-media-claim
  namespace: sonarr
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7300Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-tcp
  namespace: sonarr
  annotations:
    metallb.universe.tf/address-pool: sonarr
    metallb.universe.tf/allow-shared-ip: sonarr
  labels:
    app: sonarr
spec:
  type: LoadBalancer
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
    name: 8989-sonarr
  - protocol: TCP
    port: 80
    targetPort: 8989
    name: 80-8989-sonarr
---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sonarr
   namespace: sonarr
   labels:
     app: sonarr
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sonarr
   template:
     metadata:
       labels:
         app: sonarr

     spec:
      containers:
         - name: sonarr
           image: linuxserver/sonarr
           resources:
              requests:
                 cpu: "2"
                 memory: "1000Mi"
              limits:
                 cpu: "4"
                 memory: "2Gi"
           ports:
             - containerPort: 8989
           volumeMounts:
             - mountPath: /config
               name: sonarr-config
             - mountPath: /storage
               name: sonarr-media
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
             claimName: sonarr-pv-config-claim
        - name: sonarr-media
          persistentVolumeClaim:
             claimName: sonarr-pv-media-claim
