apiVersion: v1
kind: Namespace
metadata:
  name: sonarr
  labels:
    app: sonarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-config-volume
  namespace: sonarr
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pv-config-claim
  namespace: sonarr
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv-media-volume
  namespace: sonarr
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 18Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pv-media-claim
  namespace: sonarr
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 18Ti
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-tcp
  namespace: sonarr
  annotations:
    metallb.universe.tf/address-pool: sonarr
    metallb.universe.tf/allow-shared-ip: sonarr
  labels:
    app: sonarr
spec:
  type: LoadBalancer
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
    name: 8989-sonarr
  - protocol: TCP
    port: 80
    targetPort: 8989
    name: 80-8989-sonarr
---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sonarr
   namespace: sonarr
   labels:
     app: sonarr
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sonarr
   template:
     metadata:
       labels:
         app: sonarr
     spec:
      containers:
         - name: sonarr
           image: linuxserver/sonarr
           resources:
              limits:
                 cpu: "2"
                 memory: "4Gi"
           ports:
             - containerPort: 8989
           env:
             - name: PUID
               value: "568"
             - name: PGID
               value: "568"
           volumeMounts:
             - mountPath: /config
               name: sonarr-config
             - mountPath: /media
               name: sonarr-media
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
             claimName: sonarr-pv-config-claim
        - name: sonarr-media
          persistentVolumeClaim:
             claimName: sonarr-pv-media-claim
