apiVersion: v1
kind: PersistentVolume
metadata:
  name: bedrock-pv
  namespace: minecraft
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/bigdata/storage/configs/bedrock
    server: 192.168.1.60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bedrock-pvc
  namespace: minecraft
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
