apiVersion: v1
kind: Service
metadata:
  name: bedrock
  namespace: minecraft
  annotations:
    metallb.universe.tf/address-pool: bedrock
    metallb.universe.tf/allow-shared-ip: bedrock
  labels:
    app: bedrock
spec:
  selector:
    app: bedrock
  ports:
    - port: 19132
      targetPort: 19132
      protocol: UDP
      name: 19132-bedrock
  type: LoadBalancer
