apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: plex
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.240
    - name: sabnzbd
      protocol: layer2
      addresses:
      - 192.168.1.241-192.168.1.241
    - name: radarr
      protocol: layer2
      addresses:
      - 192.168.1.242-192.168.1.242
    - name: sonarr
      protocol: layer2
      addresses:
      - 192.168.1.243-192.168.1.243
    - name: deluge
      protocol: layer2
      addresses:
      - 192.168.1.244-192.168.1.244
    - name: zabbix
      protocol: layer2
      addresses:
      - 192.168.1.245-192.168.1.245

