apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-alert-volume
  namespace: default
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /media/bigdata/storage/configs/prometheus/
    server: 192.168.1.60
