---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sabnzbd-deployment
   namespace: sabnzbd
   labels:
     app: sabnzbd
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sabnzbd
   template:
     metadata:
       labels:
         app: sabnzbd
 
     spec:
      containers:
         - name: sabnzbd
           image: linuxserver/sabnzbd
           ports:
             - containerPort: 6789
           volumeMounts:
             - mountPath: /config
               name: sabnzbd-config
             - mountPath: /Downloads
               name: sabnzbd-downloads
      volumes:
        - name: sabnzbd-config
          persistentVolumeClaim:
             claimName: sabnzbd-pv-config-claim
        - name: sabnzbd-downloads
          persistentVolumeClaim:
             claimName: sabnzbd-pv-media-claim
---
kind: Service
apiVersion: v1
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  selector:
    app: sabnzbd
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
