---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sabnzbd
   labels:
     app: sabnzbd
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sabnzbd
   template:
     metadata:
       labels:
         app: sabnzbd
 
     spec:
      containers:
         - name: sabnzbd
           image: linuxserver/sabnzbd
           ports:
             - containerPort: 6789
           volumeMounts:
             - mountPath: /configs
               name: sabnzbd-config
             - mountPath: /complete
               name: sabnzbd-downloads
             - mountPath: /incomplete
               name: sabnzbd-incomplete
      volumes:
        - name: sabnzbd-config
          nfs:
            server: 192.168.1.60
            path: /media/bigdata/storage/
        - name: sabnzbd-downloads
          nfs:
            server: 192.168.1.60
            path: /media/bigdata/storage/Downloads
        - name: sabnzbd-incomplete
          nfs:
            server: 192.168.1.60
            path: /media/bigdata/storage/Downloads
---
kind: Service
apiVersion: v1
metadata:
  name: sabnzbd
spec:
  selector:
    app: sabnzbd
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
