apiVersion: v1
kind: Service
metadata:
  name: sonarr-tcp
  namespace: sonarr
  annotations:
    metallb.universe.tf/address-pool: sonarr
    metallb.universe.tf/allow-shared-ip: sonarr
  labels:
    app: sonarr
spec:
  type: LoadBalancer
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 32400
    targetPort: 32400
    name: 32400-sonarr


