version: '3'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - 8989:8989
    environment:
      - PUID=568
      - PGID=568
    volumes:
      - sonarr-config:/config/sonarr
      - sonarr-media:/media
    resources:
      limits:
        cpus: '2'
        memory: 2Gi
  volumes:
    sonarr-config:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /config
    sonarr-media:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /media
