apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: sonarr
  name: sonarr
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: sonarr
    metallb.universe.tf/allow-shared-ip: sonarr
  labels:
    app: sonarr
  name: sonarr-tcp
  namespace: sonarr
spec:
  ports:
  - name: 8989-sonarr
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: 80-8989-sonarr
    port: 80
    protocol: TCP
    targetPort: 8989
  selector:
    app: sonarr
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr-deployment
  namespace: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - image: linuxserver/sonarr
        name: sonarr
        ports:
        - containerPort: 8989
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0.5"
            memory: 500Mi
        volumeMounts:
        - mountPath: /config
          name: sonarr-config
        - mountPath: /storage
          name: sonarr-media
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-pv-config-claim
      - name: sonarr-media
        persistentVolumeClaim:
          claimName: sonarr-pv-media-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: sonarr-pv-config-volume
  namespace: sonarr
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /media/bigdata/storage/configs/sonarr/
    server: 192.168.1.60
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: sonarr-pv-media-volume
  namespace: sonarr
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 7300Gi
  nfs:
    path: /media/bigdata/storage
    server: 192.168.1.60
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pv-config-claim
  namespace: sonarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pv-media-claim
  namespace: sonarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 7300Gi
  storageClassName: manual
