apiVersion: v1
kind: Service
metadata:
  name: home-assistant-tcp
  namespace: home-assistant
  annotations:
    metallb.universe.tf/address-pool: home-assistant
    metallb.universe.tf/allow-shared-ip: home-assistant
  labels:
    app: home-assistant
spec:
  type: LoadBalancer
  selector:
    app: home-assistant
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
    name: 8123-home-assistant
  - protocol: TCP
    port: 80
    targetPort: 8123
    name: 80-8123-home-assistant
