ingress:
  # The Ingress class for routing external traffic to services
  class: nginx
  # The hostname for the Panel application
  panel: panel.example.com
  # The hostname for the Kuber application
  kuber: kuber.example.com
  # The issuer to use for obtaining TLS certificates
  clusterIssuer: letsencrypt-prod
panel:
  # The image for the Panel application
  image: ghcr.io/kubectyl/panel:v0.1.0-beta
  # The storage class to use for Panel's persistent volume
  # To use default K8s storage class set this value to ""
  storageClass: ""
  # The email address for Letsencrypt
  # Used for Panel only as a reference to enable cert-manager
  email: abc@gmail.com
kuber:
  # The image for the Kuber application
  image: ghcr.io/kubectyl/kuber:v1.0.0-alpha.1
mariadb:
  global:
    storageClass: ""
  # Stopping mariadb bug
  volumePermissions:
    enabled: true
  image:
    debug: true
  auth:
    # The MariaDB database name
    database: panel
    # The MariaDB username
    username: kubectyl
    # The MariaDB password for the user
    password: SecretPassword
    # The MariaDB root password
    rootPassword: SuperSecretPassword
redis:
  global:
    # The global storage class for Redis pods
    storageClass: ""