apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  namespace: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex-app
        image: linuxserver/plex
        requests:
          cpu: 750m
        limits:
          cpu: 900m
#            nvidia.com/gpu: 1
        imagePullPolicy: Always
        ports:
        - containerPort: 32400
        env:
        - name: ADVERTISE_IP
          value: "http://192.168.1.240:32400/"
        - name: VERSION
          value: "latest"
        - name: TZ
          value: "America/Toronto"
        volumeMounts:
        - name: plex-data
          mountPath: /config
        - name: plex-media
          mountPath: /storage
      volumes:
      - name: plex-data
        persistentVolumeClaim:
          claimName: plex-pv-config-claim
      - name: plex-media
        persistentVolumeClaim:
          claimName: plex-pv-media-claim
