apiVersion: v1
kind: Service
metadata:
  name: plex-tcp
  namespace: plex
  annotations:
    metallb.universe.tf/address-pool: plex
    metallb.universe.tf/allow-shared-ip: plex
  labels:
    app: kube-plex
spec:
  type: LoadBalancer
  selector:
    app: kube-plex
  ports:
  - protocol: TCP
    port: 32400
    targetPort: 32400
    name: 32400-plex


