apiVersion: v1
kind: Namespace
metadata:
  name: sabnzbd
  labels:
    app: sabnzbd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-pv-config-volume
  namespace: sabnzbd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /config/sabnzbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-pv-config-claim
  namespace: sabnzbd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-pv-media-volume
  namespace: sabnzbd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 18000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-pv-media-claim
  namespace: sabnzbd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 18000Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-tcp
  namespace: sabnzbd
  annotations:
    metallb.universe.tf/address-pool: sabnzbd
    metallb.universe.tf/allow-shared-ip: sabnzbd
  labels:
    app: sabnzbd
spec:
  type: LoadBalancer
  selector:
    app: sabnzbd
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: 8080-sabnzbd
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: 80-8080-sabnzbd
---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sabnzbd
   namespace: sabnzbd
   labels:
     app: sabnzbd
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sabnzbd
   template:
     metadata:
       labels:
         app: sabnzbd
     spec:
      containers:
         - name: sabnzbd
           image: linuxserver/sabnzbd
           resources:
              limits:
                 cpu: "2"
                 memory: "2Gi"
           ports:
             - containerPort: 8080
           env:
             - name: PUID
               value: "568"
             - name: PGID
               value: "568"
           volumeMounts:
             - mountPath: /config
               name: sabnzbd-config
             - mountPath: /media
               name: sabnzbd-media
      volumes:
        - name: sabnzbd-config
          persistentVolumeClaim:
             claimName: sabnzbd-pv-config-claim
        - name: sabnzbd-media
          persistentVolumeClaim:
             claimName: sabnzbd-pv-media-claim
