apiVersion: v1
kind: Namespace
metadata:
  name: sabnzbd
  labels:
    app: sabnzbd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-pv-config-volume
  namespace: sabnzbd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/bigdata/storage/configs/sabnzbd/
    server: 192.168.1.60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-pv-config-claim
  namespace: sabnzbd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-pv-media-volume
  namespace: sabnzbd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 7300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/bigdata/storage
    server: 192.168.1.60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-pv-media-claim
  namespace: sabnzbd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7300Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-tcp
  namespace: sabnzbd
  annotations:
    metallb.universe.tf/address-pool: sabnzbd
    metallb.universe.tf/allow-shared-ip: sabnzbd
  labels:
    app: sabnzbd
spec:
  type: LoadBalancer
  selector:
    app: sabnzbd
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: 8080-sabnzbd
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: 80to8080-sabnzbd
---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sabnzbd
   namespace: sabnzbd
   labels:
     app: sabnzbd
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sabnzbd
   template:
     metadata:
       labels:
         app: sabnzbd

     spec:
      containers:
         - name: sabnzbd
           image: linuxserver/sabnzbd
           resources:
             limits:
                cpu: "1"
             requests:
                cpu: "0.5"
           ports:
             - containerPort: 6789
           volumeMounts:
             - mountPath: /config
               name: sabnzbd-config
             - mountPath: /storage
               name: sabnzbd-media
      volumes:
        - name: sabnzbd-config
          persistentVolumeClaim:
             claimName: sabnzbd-pv-config-claim
        - name: sabnzbd-media
          persistentVolumeClaim:
             claimName: sabnzbd-pv-media-claim
