apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-tcp
  namespace: sabnzbd
  annotations:
    metallb.universe.tf/address-pool: sabnzbd
    metallb.universe.tf/allow-shared-ip: sabnzbd
  labels:
    app: sabnzbd
spec:
  type: LoadBalancer
  selector:
    app: sabnzbd
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: 8080-sabnzbd
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: 80to8080-sabnzbd

