apiVersion: v1
kind: Endpoints
metadata:
  name: radarr
  namespace: radarr
  labels:
    app: radarr
subsets:
- addresses:
  - ip: 192.168.1.200
  ports:
  - port: 7878
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-ingress
  namespace: radarr
spec:
  rules:
  - host: radarr.control.local
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 80
