apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-pv-config-volume
  namespace: radarr
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/bigdata/storage/configs/radarr/
    server: 192.168.1.60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pv-config-claim
  namespace: radarr
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
