apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: radarr
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7878
    name: radarr80
#  - protocol: TCP
#    port: 7878
#    targetPort: 7878
#    name: radarr7878
---
apiVersion: v1
kind: Endpoints
metadata:
  name: radarr
  namespace: radarr
  labels:
    app: radarr
subsets:
- addresses:
  - ip: 192.168.1.200
  ports:
  - port: 7878
    name: radarr7878
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: radarr
spec:
  rules:
  - host: radarr.control.local
    http:
      paths:
      - backend:
          service:
            name: radarr
            port:
             number: 80
        path: "/"
        pathType: Prefix
