apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonsforest-pv
  namespace: steam
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/steam/sonsforest
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonsforest-steam-pv
  namespace: steam
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/steam/opt/sonsforest
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonsforest-pvc
  namespace: steam
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonsforest-steam-pvc
  namespace: steam
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi