apiVersion: v1
kind: Service
metadata:
  name: sonsforest
  namespace: steam
  annotations:
    metallb.universe.tf/address-pool: sonsforest
    metallb.universe.tf/allow-shared-ip: sonsforest
  labels:
    app: sonsforest
spec:
  type: LoadBalancer
  selector:
    app: sonsforest
  ports:
  - protocol: UDP
    port: 8766
    targetPort: 8766
    name: sonsforest-gameplay
  - protocol: UDP
    port: 27016
    targetPort: 27016
    name: sonsforest-announce
  - protocol: UDP
    port: 9700
    targetPort: 9700
    name: sonsforest-server