apiVersion: v1
kind: PersistentVolume
metadata:
  name: steam-pv
  namespace: steam
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: 192.168.1.21:3260
    iqn: iqn.2023-10.morrnet.truenas:steam-isci
    lun: 1
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steam-pvc
  namespace: steam
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi