apiVersion: v1
kind: PersistentVolume
metadata:
  name: steam-pv
  namespace: steam
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/steam
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steam-pvc
  namespace: steam
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
