---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim
  namespace: steam
  labels:
    app: valheim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valheim
  template:
    metadata:
      labels:
        app: valheim
    spec:
      containers:
      - name: valheim
        image: ubuntu:latest
        command: ["/bin/sleep", "3650d"]
        ports:
        - containerPort: 27015
        - containerPort: 27015
          protocol: UDP
        - containerPort: 27016
          protocol: UDP
        resources:
          requests:
            cpu: '0.2'
            memory: 2Gi
          limits:
            cpu: '1.0'
            memory: 4Gi
        volumeMounts:
        - mountPath: "/data"
          name: steam-config
      volumes:
      - name: steam-config
        persistentVolumeClaim:
          claimName: steam-pv-config-claim
