apiVersion: v1
kind: PersistentVolume
metadata:
  name: insurgency-pv
  namespace: steam
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/steam/insurgency
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: insurgency-steam-pv
  namespace: steam
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/steam/opt/insurgency
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insurgency-pvc
  namespace: steam
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insurgency-steam-pvc
  namespace: steam
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi