apiVersion: v1
kind: Service
metadata:
  name: valheim
  namespace: steam
  annotations:
    metallb.universe.tf/address-pool: valheim
    metallb.universe.tf/allow-shared-ip: valheim
  labels:
    app: valheim
spec:
  type: LoadBalancer
  selector:
    app: valheim
  ports:
  - protocol: UDP
    port: 27015
    targetPort: 27015
    name: valheim-gameplay
  - protocol: UDP
    port: 27016
    targetPort: 27016
    name: valheim-announce
  - protocol: UDP
    port: 2456
    targetPort: 2456
    name: valheim-server
  - protocol: UDP
    port: 2457
    targetPort: 2457
    name: valheim-query