apiVersion: v1
kind: Service
metadata:
  name: insurgency
  namespace: steam
  annotations:
    metallb.universe.tf/address-pool: insurgency
    metallb.universe.tf/allow-shared-ip: insurgency
  labels:
    app: insurgency
spec:
  type: LoadBalancer
  selector:
    app: insurgency
  ports:
  - protocol: UDP
    port: 27015
    targetPort: 27015
    name: insurgency-gameplay
  - protocol: UDP
    port: 27016
    targetPort: 27016
    name: insurgency-announce
  - protocol: UDP
    port: 2456
    targetPort: 2456
    name: insurgency-server
  - protocol: UDP
    port: 2457
    targetPort: 2457
    name: insurgency-query