---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: palworld
  namespace: steam
  labels:
    app: palworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palworld
  template:
    metadata:
      labels:
        app: palworld
    spec:
      containers:
        - name: palworld
          image: thijsvanloef/palworld-server-docker
          env:
            - name: UPDATE_ON_BOOT
              value: "true"
            - name: COMMUNITY
              value: "true"
            - name: MULTITHREAD
              value: "true"
            - name: SERVER_NAME
              value: "Dissidents Den"
            - name: SERVER_PASSWORD
              value: "K3Yst0n3"
            - name: ADMIN_PASSWORD
              value: "Peacemaker.137"
            - name: PUID
              value: "568"
            - name: PGID
              value: "568"
          volumeMounts:
            - name: palworld-pv
              mountPath: /palworld
      volumes:
        - name: palworld-pv
          persistentVolumeClaim:
            claimName: palworld-pvc
