apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-pv-media-volume
  namespace: deluge
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 7300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /media/bigdata/storage
    server: 192.168.1.60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-pv-media-claim
  namespace: deluge
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7300Gi
