apiVersion: v1
kind: Service
metadata:
  name: deluge-tcp
  namespace: deluge
  annotations:
    metallb.universe.tf/address-pool: deluge
    metallb.universe.tf/allow-shared-ip: deluge
  labels:
    app: deluge
spec:
  type: LoadBalancer
  selector:
    app: deluge
  ports:
  - protocol: TCP
    port: 8112 
    targetPort: 8112 
    name: 8112-deluge
  - protocol: TCP
    port: 80
    targetPort: 8112
    name: 80-8112-deluge

