apiVersion: v1
kind: Service
metadata:
  name: jellyfin-tcp
  namespace: jellyfin
  annotations:
    metallb.universe.tf/address-pool: jellyfin
    metallb.universe.tf/allow-shared-ip: jellyfin
  labels:
    app: jellyfin
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
  - protocol: TCP
    port: 8096
    targetPort: 8096
    name: http-tcp
  - protocol: TCP
    port: 8920
    targetPort: 8920
    name: https-tcp

