apiVersion: v1
kind: Service
metadata:
  name: jellyfin-tcp
  namespace: jellyfin
  annotations:
    metallb.universe.tf/address-pool: jellyfin
    metallb.universe.tf/allow-shared-ip: jellyfin
  labels:
    app: jellyfin
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
  - protocol: UDP
    port: 1900
    targetPort: 1900
    name: dlna-udp
  - protocol: UDP
    port: 7359
    targetPort: 7359
    name: discovery-udp

