apiVersion: v1
kind: Service
metadata:
  name: homebridge-tcp
  namespace: homebridge
  annotations:
    metallb.universe.tf/address-pool: homebridge
    metallb.universe.tf/allow-shared-ip: homebridge
  labels:
    app: homebridge
spec:
  type: LoadBalancer
  selector:
    app: homebridge
  ports:
  - protocol: TCP
    port: 7878
    targetPort: 7878
    name: 7878-homebridge
  - protocol: TCP
    port: 80
    targetPort: 7878
    name: 80to7878-homebridge

