---
- name: Mount NFS Share and Update /etc/fstab
  hosts: k8s_nodes
  become: true  # Run tasks as sudo

  tasks:
    - name: Create mount point directory if it doesn't exist
      file:
        path: /mnt/steam
        state: directory
        mode: '0755'

    - name: Mount NFS share
      mount:
        path: /mnt/steam
        src: "192.168.1.21:/mnt/vol2/steam"
        fstype: nfs
        opts: defaults
        state: mounted

    - name: Add entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ item.fstab_entry }}"
        state: present
      loop:
        - fstab_entry: "192.168.1.21:/mnt/vol2/steam /mnt/steam nfs defaults 0 0"
